# Generated by Django 2.1.7 on 2019-03-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190301_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartword',
            old_name='weigth',
            new_name='weight',
        ),
    ]
