# Generated by Django 2.1.7 on 2019-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190302_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartword',
            name='word_two',
            field=models.CharField(default='', max_length=100, verbose_name='Слово второе'),
        ),
        migrations.AlterField(
            model_name='smartword',
            name='word_one',
            field=models.CharField(max_length=100, verbose_name='Слово первое'),
        ),
    ]
