# Generated by Django 2.1.7 on 2019-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190302_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartword',
            name='negative_count',
            field=models.IntegerField(default=0, verbose_name='Количество документов с отрицательной оценкой'),
        ),
        migrations.AddField(
            model_name='smartword',
            name='positive_count',
            field=models.IntegerField(default=0, verbose_name='Количество документов с положительной оценкой'),
        ),
    ]
