# Generated by Django 2.1.7 on 2019-03-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190307_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartword',
            old_name='weight',
            new_name='weight2',
        ),
    ]
