# Generated by Django 2.1.7 on 2019-03-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190307_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartword',
            name='negative_count',
            field=models.IntegerField(default=1, verbose_name='Количество документов с отрицательной оценкой'),
        ),
        migrations.AlterField(
            model_name='smartword',
            name='positive_count',
            field=models.IntegerField(default=1, verbose_name='Количество документов с положительной оценкой'),
        ),
    ]
